### ISSUE TITLE
Still in need of updating/support?

### ISSUE THREAD

**Issue by MaxLeiter** [siefkenj/MailMerge#1]
I opened Thunderbird a while ago and remember seeing a message about MailMerge not being updated to new APIs or something. Can't find the message now, sorry if it wasn't MailMerge, but are the problems solved? Or is there still work to be done?

**Comment by siefkenj** [comment]
What version of TB are you using? It works without warning for me in TB 68

**Comment by MaxLeiter** [comment]
It wasn't a TB message, it was a message from (I thought) the creator of MailMerge.

**Comment by siefkenj** [comment]
Oh. It wasn't from me...
