### ISSUE TITLE
Is it possible to send personalized bulk message to each contact on a specific list?

### ISSUE THREAD

**Issue by joomlagate** [siefkenj/MailMerge#11]
After the first batch of bulk emails, I saved all those receipient as contacts in a specific list of my Addressbook (or Cardbook) in Thunderbird.

Now, I want to send out personalized bulk messages to all contacts in such a specific list. But I can not find an option of "use list as recipient" in this Mail Merge add-on for Thunderbird.

Could you please add this feature?

Thank you.

**Comment by ovari** [comment]
Does the `Mail Merge` add-on below work?
https://addons.thunderbird.net/thunderbird/addon/mail-merge/
