### ISSUE TITLE
Possibility of Reply-To in Bulk-Mails

### ISSUE THREAD

**Issue by moe535** [siefkenj/MailMerge#12]
Hello there,
thanks for the greatful tool. Only thing missing in my opinion is the setting of a "Reply-To".

Thanks a lot.

**Comment by siefkenj** [comment]
What does the "Reply-To" field do? I see it's hidden in the Thunderbird interface...

**Comment by moe535** [comment]
It sets the address, that is used as default (To), when someone clicks on 'Reply'.

**Comment by siefkenj** [comment]
This should work in version >= 2.4 https://addons.thunderbird.net/en-US/thunderbird/addon/mail-merge-p/?src=search
