### ISSUE TITLE
Mail Merge does not interpolate variables in the Body field of emails after updating to Thunderbird 78.8.0 for accounts with End-to-End Encryption enabled

### ISSUE THREAD

**Issue by fabacab** [siefkenj/MailMerge#15]
I have been using Mail Merge for a long time and greatly appreciate the work you put into this Add-On for Thunderbird.

Recently, after updating to Thunderbird 78.8.0, I am no longer able to use Mail Merge because while variables are interpolated successfully in the email headers (like the `Subject` and `To` fields), variables in the `Body` of an email are not getting interpolated. This only happens on email accounts whose Account Settings have End-to-End Encryption enabled (OpenPGP, in my case).

I can work around the issue by setting the affected accounts to use the "`None`" setting when selecting an OpenPGP key, and leaving the S/MIME public certificate field blank.

Prior to updating to Thunderbird 78.8.0 earlier this week (that version of Thunderbird was first released on February 23, 2021), Mail Merge *was* able to successfuly interpolate variables in the `Body` field of an email message even when an OpenPGP key was enabled and selected for that account. To be more precise, before updating to Thunderbird 78.8.0, I was able to send unencrypted/plaintext emails through Mail Merge as expected, but after updating Thunderbird to that version, Mail Merge is only able to replace `{{Variables}}` in email headers (like the `To`) field, not the `Body` of that message.

This makes Mail Merge far less useful because in order to use it, I have to first open the Account Settings window, disable OpenPGP support for the given account identity, and then use Mail Merge.

**Comment by fabacab** [comment]
[This recent Mozilla Thunderbird Add-Ons Review for Mail Merge](https://addons.thunderbird.net/en-US/thunderbird/addon/mail-merge/reviews/1165919/) could be related, as it describes a similar (or the same?) issue.

**Comment by siefkenj** [comment]
Can you check if this is still an issue in version 2.4? https://addons.thunderbird.net/en-US/thunderbird/addon/mail-merge-p/?src=search

**Comment by siefkenj** [comment]
MailMergeP now only works with TB >= 91, so I am closing this issue for now.
