### ISSUE TITLE
Variables aren't replaced in TO, CC and BCC

### ISSUE THREAD

**Issue by 756gzdz5** [siefkenj/MailMerge#16]
Hi,

The addon replaces variables in the subject line and the body just fine but not in any of the three address fields. 
Am I doing something wrong or is the addon broken?
<img width="484" alt="Screenshot 2021-03-02 183100" src="https://user-images.githubusercontent.com/5039747/109689305-75abeb00-7b85-11eb-8396-4c1c2a27c438.png">

**Comment by siefkenj** [comment]
You must press "enter" in the to/etc. fields before they will substitute properly.
