### ISSUE TITLE
nested variables

### ISSUE THREAD

**Issue by gamgamstylep** [siefkenj/MailMerge#2]
Question to 
Nested Variables
Variables can be nested. For example: To create individual emails only for your premium customers, you can add something like this in the To field:
{{Premium|x|{{Email}}}}

Do I understand this right: In the table "Premium"  those lines with a "x" in it will get the email?

Thank you very much

**Comment by siefkenj** [comment]
Are you asking about the original MailMerge, or MailMergeP (which this is a repository for)? MailMergeP uses the [nunjucks](https://mozilla.github.io/nunjucks/) templating engine. You can read about how to do nested variables here: https://mozilla.github.io/nunjucks/

**Comment by gamgamstylep** [comment]
sorry was for the original MailMerge.
