### ISSUE TITLE
First and last name do not show up in recipients inbox, instead it is just my email

### ISSUE THREAD

**Issue by anthonymet** [siefkenj/MailMerge#24]
I tested Mail Merge: P by doing a mass email to others at my workplace. Normally when I send an individual email it will show up in their inbox with my first and last name (I think this looks professional). When I use Mail Merge, it shows up in their inbox with my email instead (looking very unprofessional as it is all lowercase and has numbers in it). Is it possible to fix this?

**Comment by siefkenj** [comment]
Have you tried entering emails as `Name <email@foo.com>`? MailMerge P uses what you type directly. It doesn't search through the address book.
