### ISSUE TITLE
Window is too big

### ISSUE THREAD

**Issue by doudz** [siefkenj/MailMerge#3]
First, thank you so much for this addon, it's really useful !

I'm facing a problem where I can't click on "Send" on the Preview tab because when displaying the preview the window adjust the height and the "Send" button become out of the screen.

Additionnally, many laptop have only 768px height so the window is always a bit too big

Could reduce the window height and fix it to avoid auto adjustement ?
Maybe by adding scrolling on Preview tab ?

**Comment by doudz** [comment]
it happens maybe because my template email is a bit too long

**Comment by siefkenj** [comment]
Should be fixed in 2.3 :-)

**Comment by doudz** [comment]
Great ! Thank you
