### ISSUE TITLE
Blank screen with Thunderbird 115.3.1 (64-bit)

### ISSUE THREAD

**Issue by turf212** [siefkenj/MailMerge#41]
After the latest update of TB I get a blank screen when opening the Mail Merge P option on emails. Thunderbird then stops working properly and processes are left behind on close and need to be killed from the terminal.

No errors on the debugging page - just a message that the new window was opened.

**Comment by pravissw** [comment]
I can second the blank screen issue on Fedora, downgrading to 102.9.1 immediately fixes it. The add-on doesn't work with 115.3.1 for me.

I did not notice thunderbird stop working properly, or leaving behind processes.

**Comment by siefkenj** [comment]
Thank you for the report. I don't have access to TB 115 at the moment, but as soon as I do, I will investigate.

**Comment by 121sim** [comment]
I'll try to post a screenshot when it happens, but i did have a MailMerge window that was with blank options and buttons, several times. Closing the draft (or model) and re-opening it solved the issue.

**Comment by 121sim** [comment]
![Capture d’écran 2023-10-16 à 14 32 04](https://github.com/siefkenj/MailMerge/assets/74899182/cb83b31f-dc95-45bc-a15c-1b1f82217b15)

**Comment by siefkenj** [comment]
@121sim It appears that you are running `MailMerge` rather than `MailMergeP`. You need to report any errors for `MailMerge` at https://addons.thunderbird.net/en-US/thunderbird/addon/mail-merge/  (But hopefully it's working for you now!)
