### ISSUE TITLE
Blank Email With Thunderbird 115.3.1 (64 Bit) and CSV

### ISSUE THREAD

**Issue by DaGeRe** [siefkenj/MailMerge#42]
A while ago, MailMerge worked perfectly for me on Thunderbird with Fedora.

When I tried it today, with the latest Thunderbird from on Fedora, configuring the mail seems to work fine:

![grafik](https://github.com/siefkenj/MailMerge/assets/4358467/657a164b-9c9a-495a-8773-ec15bb38c59b)

And also the file is read as its supposed to:

![grafik](https://github.com/siefkenj/MailMerge/assets/4358467/5b6fecb6-5e7c-4367-9d94-a3a9ad032408)

Unfortunately, when I generate the message (both for preview and for sending), its empty:

![grafik](https://github.com/siefkenj/MailMerge/assets/4358467/957f72b8-3cc6-48db-9f98-adee53c1f746)

There were no error messages that could indicate a problem. Also, starting Thunderbird from the console does not yield any exception or other logs when executing the same workflow. Is there some solution for this issue?

**Comment by siefkenj** [comment]
@DaGeRe  It appears that you are running `MailMerge` rather than `MailMergeP`. You need to report any errors for `MailMerge` at https://addons.thunderbird.net/en-US/thunderbird/addon/mail-merge/  (But hopefully it's working for you now!)
