### ISSUE TITLE
Missing column name cause data loading fails

### ISSUE THREAD

**Issue by doudz** [siefkenj/MailMerge#5]
When there's a column without name, we got the following error
![image](https://user-images.githubusercontent.com/1262548/100359201-859cb780-2ff7-11eb-9bd7-0bcea80a503a.png)

it's not a big deal to add a column name but users often add extra data on a row without column name and don't understand why there's a error at first

it could be smart to just ignore such unamed column

**Comment by siefkenj** [comment]
I am having trouble reproducing this error. When I leave off the column names I still get a preview...Are you doing this via copy-and-paste, or via opening a spreadsheet?

**Comment by doudz** [comment]
I tried using a xls file where the first column as no name (no data in A1 cell)

**Comment by siefkenj** [comment]
Found the bug. This will be fixed in the next release :-)
